name: Unit Tests

# Needs Lua 5.1 cos that's what LOVE bundles. (Though we don't (yet?) need LOVE)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Deps
        run:
          - sudo apt-get update && sudo apt-get install -y lua5.1
          - mkdir .lib
          - curl -o .lib/fennel.lua https://fennel-lang.org/downloads/fennel-1.6.1.lua
          - curl -o .lib/faith.fnl https://git.sr.ht/~technomancy/faith/blob/main/faith.fnl

      - name: Run Fennel Unit Tests
        env:
          FENNEL_PATH: ".lib/?.fnl"
        run: lua5.1 .lib/fennel.lua test/run.fnl
